export const APP_JSON = 'application/json';
export const APP_NAME = '🔒💬 Secure Chat - '
export const BEAT_LOADER_SIZE = 8;
export const CHAT_LOAD_FAILURE_MSG = 'Failed to load messages';
export const COMMON_HEADERS = { 'Content-Type': APP_JSON };
export const COPY_SUCCESS_MSG = 'Copied';
export const COPY_TIMEOUT = 2000;
export const DEFAULT_MODEL = 'gpt-4';
export const DEFAULT_USER_ROLE = 'user';
export const LANGUAGE_CPP = 'cpp';
export const LANGUAGE_C_PP = 'c++';
export const LOADING = 'Loading...';
export const LOGIN_BUTTON_LABEL = 'Login';
export const LOGIN_ERROR = 'There was an error logging in. Please try again.';
export const LOGIN_PROMPT = 'Enter your username'
export const PROMPT_ROLE = 'user';
export const RESPONSE_ERROR_MSG = 'Unexpected response structure';
export const SECOND = 1000;
export const SPINNER_CSS_COLOR = '#123abc';
export const TIMESTAMP_PATTERN = 'yyyy-mm-dd-hh:mm:ss';
export const TITLE = 'Welcome! Please Login';